server:
  port: 10000

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:oracle:thin:@localhost:1521:XE
    username: hr
    password: hr
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
#      drop하고 create
      ddl-auto: create
#      drop하고 create하고 drop (sqlSession 종료 시점)
#      ddl-auto: create-drop
#      필드 변경 시 alter 실행
#      ddl-auto: update
#      필드 변경 시 RDB와 다르면 오류
#      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: always